version: "3"
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  api:
    env_file:
      - .env
    build:
      context: ./back
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./back:/back:rw,consistent
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build: "./client"
    volumes:
      - "./client:/home/node/app:rw,consistent"
    working_dir: "/home/node/app"
    command: "yarn serve"
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:8080:8080
    depends_on:
      - api
