
### New user
POST http://localhost:5000/api/user/new

{
    "email":"lolo@gmail.com",
    "password":"secret"
}


### Login
POST http://localhost:5000/api/user/login
{
    "email":"lolo@gmail.com",
    "password":"secret"
}