
### New user
POST http://localhost:5000/users

{
    "email":"lolo@gmail.com",
    "password":"secret"
}


### Login
POST http://localhost:5000/login

{
    "email":"lolo@gmail.com",
    "password":"secret"
}